# Generated by Django 5.2 on 2025-04-16 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='answer_type',
            field=models.CharField(choices=[('user', 'User'), ('AI', 'AI')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
